In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Numpy

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

## Creating numpy arrays

### Directly

In [4]:
a = np.array(
    [[1.0, 2.0, 3.0], 
     [4.0, 5.0, 6.0], 
     [7.0, 8.0, 9.0]]
)

print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### From a list

In [5]:
a = [[1.0, 2.0, 3.0], 
     [4.0, 5.0, 6.0], 
     [7.0, 8.0, 9.0]]

print(a)
print()

a = np.array(a)

print(a)

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### From a list comprehension

In [4]:
a = [i**2 for i in range(10)]

print(a)
print()
print(np.array(a))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

[ 0  1  4  9 16 25 36 49 64 81]


### Ready-made functions in numpy

In [5]:
# All zeros
a = np.zeros((3, 4))
print("All zeros")
print(a)
print()

# All a chosen value
a = np.full((3, 4), 7.0)
print("All chosen value (variant 1)")
print(a)
print()

# or

a = np.zeros((3, 4))
a[:] = 7.0
print("All chosen value (variant 2)")
print(a)
print()

# Random integers

a = np.random.randint(low=0, high=10, size=(3, 2))
print("Random integers")
print(a)
print()

# Random values from the normal distribution (Gaussian)

print("Random values from the normal distribution")
a = np.random.normal(loc=0, scale=10, size=(3, 2))
print(a)

All zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

All chosen value (variant 1)
[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]

All chosen value (variant 2)
[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]

Random integers
[[3 8]
 [1 1]
 [3 7]]

Random values from the normal distribution
[[  5.71403086   8.93132422]
 [ -7.40482782  14.87782321]
 [-19.80414183  -3.91461296]]


## Slicing numpy arrays

### Slicing in 1D

To obtain only specific values from a numpy array one can use so called slicing. It has the form

**arr[low:high:step]**

where low is the lowest index to be retrieved, high is the lowest index not to be retrieved and step indicates that every step element will be taken.

In [6]:
a = [i**2 for i in range(10)]

print("Original: ", a)
print("First 5 elements:", a[:5])
print("Elements from index 3 to index 5:", a[3:6])
print("Last 3 elements (negative indexing):", a[-3:])
print("Printed in reverse order:", a[::-1])
print("Every second element:", a[::2])

Original:  [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
First 5 elements: [0, 1, 4, 9, 16]
Elements from index 3 to index 5: [9, 16, 25]
Last 3 elements (negative indexing): [49, 64, 81]
Printed in reverse order: [81, 64, 49, 36, 25, 16, 9, 4, 1, 0]
Every second element: [0, 4, 16, 36, 64]


### Slicing in 2D

In two dimensions it works similarly, just the slicing is separate for every dimension.

In [7]:
a = np.array([i for i in range(25)]).reshape(5, 5)

print("Original: ")
print(a)
print()
print("First 2 elements of the first 3 row:")
print(a[:3, :2])
print()
print("Middle 3 elements from the middle 3 rows:")
print(a[1:4, 1:4])
print()
print("Bottom-right 3 by 3 submatrix (negative indexing):")
print(a[-3:, -3:])
print()
print("Reversed columns:")
print(a[:, ::-1])
print()

Original: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

First 2 elements of the first 3 row:
[[ 0  1]
 [ 5  6]
 [10 11]]

Middle 3 elements from the middle 3 rows:
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]

Bottom-right 3 by 3 submatrix (negative indexing):
[[12 13 14]
 [17 18 19]
 [22 23 24]]

Reversed columns:
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]]



### Setting numpy array field values

In [8]:
a = np.array([i for i in range(25)]).reshape(5, 5)

print("Original: ")
print(a)
print()

a[1:4, 1:4] = 5.0

print("Middle values changed to 5")
print(a)
print()

b = np.array([i**2 - i for i in range(9)]).reshape(3, 3)

print("Second matrix")
print(b)
print()

a[1:4, 1:4] = b

print("Second matrix substituted into the middle of the first matrix")
print(a)

Original: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Middle values changed to 5
[[ 0  1  2  3  4]
 [ 5  5  5  5  9]
 [10  5  5  5 14]
 [15  5  5  5 19]
 [20 21 22 23 24]]

Second matrix
[[ 0  0  2]
 [ 6 12 20]
 [30 42 56]]

Second matrix substituted into the middle of the first matrix
[[ 0  1  2  3  4]
 [ 5  0  0  2  9]
 [10  6 12 20 14]
 [15 30 42 56 19]
 [20 21 22 23 24]]


## Operations on numpy arrays

It is important to remember that arithmetic operations on numpy arrays are always element-wise.

In [9]:
a = np.array([i**2 for i in range(9)]).reshape((3, 3))
print(a)
print()

b = np.array([i**0.5 for i in range(9)]).reshape((3, 3))
print(b)
print()

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]



### Element-wise sum

In [10]:
print(a + b)

[[ 0.          2.          5.41421356]
 [10.73205081 18.         27.23606798]
 [38.44948974 51.64575131 66.82842712]]


### Element-wise multiplication

In [11]:
print(a * b)

[[  0.           1.           5.65685425]
 [ 15.58845727  32.          55.90169944]
 [ 88.18163074 129.64181424 181.01933598]]


### Matrix multiplication

In [12]:
print(np.matmul(a, b))
print()

# Multiplication by the identity matrix (to check it works as expected)
id_matrix = np.array([[1.0, 0.0, 0.0], 
                      [0.0, 1.0, 0.0], 
                      [0.0, 0.0, 1.0]])

print(np.matmul(id_matrix, a))

[[ 11.53000978  12.58300524  13.54977648]
 [ 88.95005649 107.14378278 119.21568782]
 [241.63783311 303.32808391 341.49835513]]

[[ 0.  1.  4.]
 [ 9. 16. 25.]
 [36. 49. 64.]]


### Calculating the mean

In [13]:
a = np.random.randint(low=0, high=10, size=(5))

print(a)
print()

print("Mean (by sum): ", np.sum(a) / len(a))
print("Mean (by mean):", np.mean(a))

[1 9 1 1 3]

Mean:  3.0


### Calculating the mean of every row

In [14]:
a = np.random.randint(low=0, high=10, size=(5, 3))

print(a)
print()
print(a.shape)
print()

print("Mean:", np.sum(a, axis=1) / a.shape[1])

print("Mean in the original matrix form:")
print((np.sum(a, axis=1) / a.shape[1]).reshape(-1, 1))  # -1 calculates the right size to use all elements

[[7 7 9]
 [8 2 9]
 [4 3 5]
 [1 5 4]
 [8 0 8]]

Mean: [7.66666667 6.33333333 4.         3.33333333 5.33333333]
Mean in the original matrix form:
[[7.66666667]
 [6.33333333]
 [4.        ]
 [3.33333333]
 [5.33333333]]


### More complex operations

In [15]:
a = [1.0, 2.0, 3.0]

print("Vector to power 2 (element-wise)")
print(np.power(a, 2))
print()
print("Euler number to the power a (element-wise)")
print(np.exp(a))
print()
print("An even more complex expression")
print((np.power(a, 2) + np.exp(a)) / np.sum(a))

Vector to power 2 (element-wise)
[1. 4. 9.]

Euler number to the power a (element-wise)
[ 2.71828183  7.3890561  20.08553692]

An even more complex expression
[0.61971364 1.89817602 4.84758949]


## Numpy tasks

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [8]:
x = np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25])

sigmoid = lambda y: 1 / (1 + np.exp(-y))

vfunc = np.vectorize(sigmoid)
ans = vfunc(x)

print(ans[-5:])

[0.549834   0.47502081 0.52497919 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (x.T).

In [9]:
𝑥=np.array([3,1,4,2,6,1,4,8])
𝑦=np.array([5,2,3,12,2,4,17,11])

a = np.sum(x*y)
print('a ->', a)

b = np.dot(x, y)
print('b ->', b)

c = np.matmul(x.T, y)
print('c ->', c)

a -> 225
b -> 225
c -> 225


**Task 3.** Calculate the following expression<br/>
$$\frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, -2.1, -3.3, 0.2]$<br/>
$\theta = [7.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, 1.65]$<br/>
and print the result. Use only vector operations.

In [254]:
# Incorrect!
x = np.array([1.2,2.3,3.4,-0.7,4.2,2.7,-0.5,-2.1,-3.3,0.2])

theta = np.array([7.7,0.33,-2.12,-1.73,2.9,-5.8,-0.9,12.11,3.43,-0.5,1.65])

ans = 1/(1+np.exp(np.sum((-x * theta[:10]))-theta[10]))

print(ans)

1.3644840814871147e-15


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [11]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

## Peek into the datasets

In [12]:
steam_df.head(10)

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0
5  151603712                       Spore          play   14.9     0
6  151603712           Fallout New Vegas      purchase    1.0     0
7  151603712           Fallout New Vegas          play   12.1     0
8  151603712               Left 4 Dead 2      purchase    1.0     0
9  151603712               Left 4 Dead 2          play    8.9     0

In [13]:
ml_ratings_df.head(10)

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931
5       1       70     3.0  964982400
6       1      101     5.0  964980868
7       1      110     4.0  964982176
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [14]:
ml_movies_df.head(10)

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

## Merge both MovieLens DataFrames into one

In [24]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

## Choosing a row, a column or several columns

In [25]:
display(HTML(steam_df.head(10).to_html()))

# Choosing rows by index
chosen_df = steam_df[3:6]

print("Choosing rows by index")
display(HTML(chosen_df.head(10).to_html()))

# Choosing rows by position
chosen_df = steam_df.iloc[3:6]

print("Choosing rows by position")
display(HTML(chosen_df.head(10).to_html()))

Choosing rows by index


Choosing rows by position


In [26]:
# Choosing a column
chosen_df = steam_df['game-title']

print(chosen_df.head(10))

0    The Elder Scrolls V Skyrim
1    The Elder Scrolls V Skyrim
2                     Fallout 4
3                     Fallout 4
4                         Spore
5                         Spore
6             Fallout New Vegas
7             Fallout New Vegas
8                 Left 4 Dead 2
9                 Left 4 Dead 2
Name: game-title, dtype: object


In [27]:
# Choosing several columns
chosen_df = steam_df[['user-id', 'game-title']]

display(HTML(chosen_df.head(10).to_html()))

### Splitting the dataset into training and test set

In [15]:
shuffle = np.array(list(range(len(steam_df))))

# alternatively

shuffle = np.arange(len(steam_df))

np.random.shuffle(shuffle)
# shuffle = list(shuffle)
print("Shuffled range of indices")
print(shuffle[:20])
print()

train_test_split = 0.8
split_index = int(len(steam_df) * train_test_split)

training_set = steam_df.iloc[shuffle[:split_index]]
test_set = steam_df.iloc[shuffle[split_index:]]

display(HTML(training_set.head(10).to_html()))

display(HTML(test_set.head(10).to_html()))

print(len(training_set))
print(len(test_set))

Shuffled range of indices
[157904, 35114, 46281, 137296, 169680, 60414, 104937, 19299, 13870, 8310, 131777, 74734, 123378, 172034, 62540, 40853, 72462, 26734, 63892, 182820]



## Filtering

### Filtering columns

In [29]:
chosen_df = steam_df.loc[:, ['user-id', 'game-title']]

display(HTML(chosen_df.head(10).to_html()))

### Filtering rows

In [30]:
condition = steam_df['game-title'] == 'Fallout 4'

print(condition.head(10))

chosen_df = steam_df.loc[condition]

display(HTML(chosen_df.head(10).to_html()))

0    False
1    False
2     True
3     True
4    False
5    False
6    False
7    False
8    False
9    False
Name: game-title, dtype: bool


### Filtering rows and columns at once

In [31]:
condition = (steam_df['game-title'] == 'Fallout 4') & (steam_df['behavior-name'] == 'play')

chosen_df = steam_df.loc[condition, ['user-id', 'game-title', 'value']]

display(HTML(chosen_df.head(10).to_html()))

## Simple operations on columns

### Multiply a column by 2

In [32]:
steam_df_copy = steam_df.copy()

display(HTML(steam_df_copy.head(10).to_html()))

steam_df_copy.loc[:, 'value'] = steam_df_copy['value'] * 2

display(HTML(steam_df_copy.head(10).to_html()))

### Choose the first n letters of a string

In [33]:
ml_movies_df_copy = ml_movies_df.copy()

display(HTML(ml_movies_df_copy.head(10).to_html()))

ml_movies_df_copy.loc[:, 'title'] = ml_movies_df_copy['title'].str[:6]

display(HTML(ml_movies_df_copy.head(10).to_html()))

### Take the mean of a column

In [34]:
# Option 1
print(steam_df['value'].mean())

# Option 2
print(np.mean(steam_df['value']))

17.874384000000475
17.874384000000475


### Simple operation on filtered data

In [35]:
steam_df_copy = steam_df.loc[((steam_df['game-title'] == 'Fallout 4') | (steam_df['game-title'] == 'The Elder Scrolls V Skyrim')) 
                             & (steam_df['behavior-name'] == 'play')].copy()

display(HTML(steam_df_copy.head(10).to_html()))

condition = (steam_df_copy['game-title'] == 'Fallout 4') & (steam_df_copy['behavior-name'] == 'play')

steam_df_copy.loc[condition, 'value'] = steam_df_copy.loc[condition, 'value'] * 2

display(HTML(steam_df_copy.head(10).to_html()))

## Advanced operations on columns

In [36]:
def reduce_outliers(x):
    return min(np.log(1 + x), 4)

steam_df_copy = steam_df.loc[steam_df['behavior-name'] == 'play'].copy()

display(HTML(steam_df_copy.head(10).to_html()))

steam_df_copy.loc[:, 'value'] = steam_df_copy['value'].apply(reduce_outliers)

display(HTML(steam_df_copy.head(10).to_html()))

### The same apply operation can be achieved with the use of a lambda function

In [37]:
steam_df_copy = steam_df.loc[steam_df['behavior-name'] == 'play'].copy()

display(HTML(steam_df_copy.head(10).to_html()))

steam_df_copy.loc[:, 'value'] = steam_df_copy['value'].apply(lambda x: min(np.log(1 + x), 4))

display(HTML(steam_df_copy.head(10).to_html()))

### Apply on two columns at once

In [38]:
steam_df_copy = steam_df.loc[steam_df['behavior-name'] == 'play'].copy()

display(HTML(steam_df_copy.head(10).to_html()))

steam_df_copy.loc[:, 'value_2'] = steam_df_copy['value'].apply(lambda x: min(np.log(1 + x), 4))

display(HTML(steam_df_copy.head(10).to_html()))

steam_df_copy.loc[:, 'value'] = steam_df_copy[['value', 'value_2']].apply(lambda x: x[0] * x[1], axis=1)

display(HTML(steam_df_copy.head(10).to_html()))

In [39]:
ml_movies_df_copy = ml_movies_df.copy()

display(HTML(ml_movies_df_copy.head(10).to_html()))

ml_movies_df_copy.loc[:, 'title|genres'] = ml_movies_df_copy[['title', 'genres']].apply(lambda x: x[0] + "|" + x[1], axis=1)

display(HTML(ml_movies_df_copy.head(10).to_html()))

## Grouping and aggregating

### Find the most popular games (in terms of purchases)

In [40]:
steam_grouped = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['game-title', 'value']]
steam_grouped = steam_grouped.groupby('game-title').sum()
display(HTML(steam_grouped.head(10).to_html()))

steam_grouped = steam_grouped.sort_values(by='value', ascending=False).reset_index()

display(HTML(steam_grouped.head(10).to_html()))

## Iterating over a DataFrame (if possible, use column operations instead)

In [41]:
i = 0
for idx, row in steam_df.iterrows():
    print("[{}, {}, {}, {}]".format(idx, row['user-id'], row['game-title'], row['behavior-name']))
    i += 1
    if i == 10:
        break

[151603712, The Elder Scrolls V Skyrim, purchase]
[151603712, The Elder Scrolls V Skyrim, play]
[151603712, Fallout 4, purchase]
[151603712, Fallout 4, play]
[151603712, Spore, purchase]
[151603712, Spore, play]
[151603712, Fallout New Vegas, purchase]
[151603712, Fallout New Vegas, play]
[151603712, Left 4 Dead 2, purchase]
[151603712, Left 4 Dead 2, play]


## Pandas tasks - Steam dataset

**Task 4.** How many people made a purchase in the Steam dataset? Remember that a person could by many games, but you need to count every person once.

In [50]:
condition_one = steam_df['behavior-name'] == 'purchase'

purchase = steam_df.loc[condition_one, 'user-id']
# display(HTML(n_purchase.head(10).to_html()))

n_unique = purchase.nunique()

print(n_unique)

12393


**Task 5.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [53]:
condition_one = steam_df['game-title'] == 'The Elder Scrolls V Skyrim'
condition_two = steam_df['behavior-name'] == 'purchase'
    
purchase = steam_df.loc[condition_one & condition_two, 'user-id']
# display(HTML(purchase.to_html()))

n_unique = purchase.nunique()

print(n_unique)

717


**Task 6.** How many purchases people made on average?

In [62]:
condition_one = steam_df['behavior-name'] == 'purchase'

group_users_by_id = steam_df.loc[condition_one].groupby('user-id')

purchase_mean = group_users.sum()['value'].mean()

print(purchase_mean)

10.45033486645687


**Task 7.** Who bought the most games?

In [73]:
condition_one = steam_df['behavior-name'] == 'purchase'

users_purchase = steam_df.loc[condition_one,  ['user-id', 'value']]
# display(HTML(users_purchase.to_html()))

group_users_by_id = users_purchase.groupby('user-id')

sort_users = group_users_by_id.sum().sort_values(by='value', ascending=False)

best_user = sort_users.head(1)

print(best_user)

           value
user-id         
62990992  1075.0


**Task 8.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [74]:
condition_one = steam_df['behavior-name'] == 'play'
condition_two = steam_df['game-title'] == 'The Elder Scrolls V Skyrim'


users_values = steam_df.loc[condition_one & condition_two, ['value']]

average_hours = users_values.mean()

print(average_hours)

value    104.710931
dtype: float64


**Task 9.** Which games were played the most (in terms of the number of hours played)? Print the first 10 titles and respective numbers of hours.

In [97]:
condition_one = steam_df['behavior-name'] == 'play'

games = steam_df.loc[condition_one, ['value', 'game-title']]

sum_games_values = games.groupby('game-title').sum()

sort_games_by_value = sum_games_values.sort_values(by='value', ascending=False)

best_games = sort_games_by_value.head(10)

display(HTML(best_games.to_html()))

**Task 10.** Which games are the most consistently played (in terms of the average number of hours played)? Print the first 10 titles and respective numbers of hours.

In [98]:
condition_one = steam_df['behavior-name'] == 'play'

games = steam_df.loc[condition_one, ['value', 'game-title']]

avg_games_values = games.groupby('game-title').mean()

sort_games_by_value = avg_games_values.sort_values(by='value', ascending=False)

best_games = sort_games_by_value.head(10)

display(HTML(best_games.to_html()))

**Task 11\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [126]:
condition_one = steam_df['behavior-name'] == 'play'
condition_two = steam_df['behavior-name'] == 'purchase'

play = steam_df.loc[condition_one, ['user-id', 'game-title', 'value']]

purchase = steam_df.loc[condition_two, ['user-id', 'game-title', 'value']]
purchase['value'] = 0.0

purchase_duplicates = steam_df.loc[condition_one, ['user-id', 'game-title', 'value']]
purchase_duplicates['value'] = 0.0

# display(HTML(purchase.to_html()))
# display(HTML(purchase_duplicates.to_html()))
# display(HTML(play.to_html()))

# remove duplicates from purchase using purchase_duplicates (purchase-purchase_duplicates)
purchase_clean = pd.merge(purchase, purchase_duplicates, on=['user-id', 'game-title', 'value'], how='outer', indicator=True).query("_merge != 'both'").drop('_merge', axis=1).reset_index(drop=True)

concat_games = pd.concat([play, purchase_clean])

# display(HTML(concat_games.to_html()))

# test_one = concat_games.loc[concat_games['value'] == 0.0]
# display(HTML(test_one.to_html()))


avg_games_values = concat_games[['game-title', 'value']].groupby('game-title').mean()

sort_games_by_value = avg_games_values.sort_values(by='value', ascending=False)

best_games = sort_games_by_value.head(10)

display(HTML(best_games.to_html()))

**Task 12.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print the first 10 rows from the entire Steam dataset after this change.

In [133]:
condition_one = steam_df['behavior-name'] == 'play'

sigmoid = lambda x: 1 / (1 + np.exp(-0.01 * x))

played_games = steam_df.loc[condition_one].copy()
played_games[['value']] = played_games['value'].apply(sigmoid)

display(HTML(played_games.head(50).to_html()))

## Pandas tasks - MovieLens dataset

**Task 13\*.** Calculate popularity (by the number of users who watched a movie) of all genres.

In [138]:
movies = pd.merge(ml_ratings_df, ml_movies_df, on='movieId');
movies['genres'] = movies['genres'].str.split("|")

# display(HTML(movies.head(10).to_html()))

movies = movies.explode('genres').reset_index(drop=True)

# display(HTML(movies.head(10).to_html()))

movies_group_by_genre = movies.groupby('genres')

movies_by_title = movies_group_by_genre.count().sort_values(by='title', ascending=False)

movies_top = movies_by_title[['title']].head(10)

display(HTML(movies_top.to_html()))

**Task 14\*.** Calculate average rating for all genres.

In [166]:
movies = pd.merge(ml_ratings_df, ml_movies_df, on='movieId');
movies['genres'] = movies['genres'].str.split("|")

# display(HTML(movies.head(10).to_html()))

movies = movies.explode('genres').reset_index(drop=True)

# display(HTML(movies.head(10).to_html()))

movies_group_by_genre = movies.groupby('genres')

movies_avg = movies_group_by_genre.mean().sort_values(by='rating')

movies_format = movies_avg[['rating']]

display(HTML(movies_format.to_html()))

**Task 15.** Calculate each movie rating bias (deviation from the mean of all movies average ratings). Print first 10 in the form: title, average rating, bias.

In [223]:
movies = pd.merge(ml_ratings_df, ml_movies_df, on='movieId');

# display(HTML(movies.head(10).to_html()))

movies_group_by_title = movies.groupby('title')

movies_avg = movies_group_by_title.mean('rating')
# display(HTML(movies_avg.to_html()))

general_avg = movies['rating'].mean()
# print(general_avg)

movies_avg.loc[:, 'bias'] =  np.abs(movies_avg['rating'] - general_avg)

# movies_sort_by_bias = movies_avg.sort_values(by='bias')

movies_format = movies_avg[['rating', 'bias']]

display(HTML(movies_format.to_html()))

**Task 16.** Calculate each user rating bias (deviation from the mean of all users average ratings). Print first 10 in the form: user_id, average rating, bias.

In [224]:
movies = pd.merge(ml_ratings_df, ml_movies_df, on='movieId');
# display(HTML(movies.head(10).to_html()))

general_avg = movies['rating'].mean()
# print(general_avg)

movies_group_by_userId = movies.groupby('userId')
users_movies_avg = movies_group_by_userId.mean('rating')

users_movies_avg.loc[:, 'bias'] = np.abs(users_movies_avg['rating'] - general_avg)

# movies_sort_by_bias = users_movies_avg.sort_values(by='bias')

movies_format = users_movies_avg[['rating', 'bias']]

display(HTML(movies_format.head(10).to_html()))

**Task 17.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns (use HTML Display for that). You can iterate over the DataFrame in this task.

In [226]:
movies = pd.merge(ml_ratings_df, ml_movies_df, on='movieId');

df = movies.pivot_table(index='userId', columns='movieId', aggfunc=len, fill_value=0)

np.random.randint(193610)

ans = df.sample(n=10).sample(n=10, axis=1)

display(HTML(ans.to_html()))

## Pandas + numpy tasks

**Task 18.** Create the entire interaction matrix for the MovieLens dataset.

In [228]:
movies = pd.merge(ml_ratings_df, ml_movies_df, on='movieId');

df = movies.pivot_table(index='userId', columns='movieId', aggfunc=len, fill_value=0)

df

genres                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10       
userId                                                                          
1            1      0      1      0      0      1      0      0      0      0   
2            0      0      0      0      0      0      0      0      0      0   
3            0      0      0      0      0      0      0      0      0      0   
4            0      0      0      0      0      0      0      0      0      0   
5            1      0      0      0      0      0      0      0      0      0   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
606          1      0      0      0      0      0      1      0      0      0   
607          1      0      0      0      0      0      0      0      0      0   
608          1      1      1      0      0      0      0      0      0      1   
609          1      0      0      0      0      0      0      0      0      1   
610          1      0      0      0      0      1      0      0      0      0   

         ...  title                                                          \
movieId  ... 193565 193567 193571 193573 193579 193581 193583 193585 193587   
userId   ...                                                                  
1        ...      0      0      0      0      0      0      0      0      0   
2        ...      0      0      0      0      0      0      0      0      0   
3        ...      0      0      0      0      0      0      0      0      0   
4        ...      0      0      0      0      0      0      0      0      0   
5        ...      0      0      0      0      0      0      0      0      0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
606      ...      0      0      0      0      0      0      0      0      0   
607      ...      0      0      0      0      0      0      0      0      0   
608      ...      0      0      0      0      0      0      0      0      0   
609      ...      0      0      0      0      0      0      0      0      0   
610      ...      0      0      0      0      0      0      0      0      0   

                
movieId 193609  
userId          
1            0  
2            0  
3            0  
4            0  
5            0  
...        ...  
606          0  
607          0  
608          0  
609          0  
610          0  

[610 rows x 38896 columns]

**Task 19.** Calculate the matrix of size (n_users, n_users) where at position (i, j) is the number of movies watched both by user i and user j. Print the submatrix of first 10 rows and 10 columns.

In [249]:
movies = pd.merge(ml_ratings_df, ml_movies_df, on='movieId');

movies_out = movies.merge(movies, on='movieId')

results = pd.crosstab(movies_out.userId_x, movies_out.userId_y)
results


userId_y  1    2    3    4    5    6    7    8    9    10   ...  601  602  \
userId_x                                                    ...             
1         232    2    7   45   13   33   26   15    5    6  ...   11   27   
2           2   29    0    1    1    2    3    1    0    5  ...   11    1   
3           7    0   39    1    1    3    0    1    0    0  ...    2    2   
4          45    1    1  216   12   27   22    9    1    9  ...   15   23   
5          13    1    1   12   44   36    9   19    0    3  ...    4   31   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
606        84    5    8   96   23   64   81   23   15   40  ...   54   46   
607        60    1    4   29   15   36   28   16    1    5  ...   11   29   
608       136    6    9   74   30  111  105   40   18   27  ...   38   71   
609         9    1    0    3   10   22    6   17    0    2  ...    2   23   
610        69   18    7   53   14   31   82   17   14   53  ...   69   29   

userId_y  603  604  605   606  607  608  609   610  
userId_x                                            
1         110   12   35    84   60  136    9    69  
2           2    0    0     5    1    6    1    18  
3           9    0    1     8    4    9    0     7  
4         139    9   16    96   29   74    3    53  
5          25   19   14    23   15   30   10    14  
...       ...  ...  ...   ...  ...  ...  ...   ...  
606       309   23   73  1115   75  254   15   223  
607        95   19   23    75  187  116   12    61  
608       220   53   77   254  116  831   23   296  
609        13   14    9    15   12   23   37    10  
610       161   17   63   223   61  296   10  1302  

[610 rows x 610 columns]

**Task 20.** Calculate the matrix of size (n_items, n_items) where at position (i, j) is the number of users who watched both movie i and movie j. Print the submatrix of first 10 rows and 10 columns.

In [251]:
movies = pd.merge(ml_ratings_df, ml_movies_df, on='movieId');

movies_out = movies.merge(movies, on='userId')

results = pd.crosstab(movies_out.movieId_x, movies_out.movieId_y)
results

movieId_y  1       2       3       4       5       6       7       8       \
movieId_x                                                                   
1             215      68      32       2      32      58      32       5   
2              68     110      26       3      22      36      18       6   
3              32      26      52       1      19      25      19       4   
4               2       3       1       7       3       2       6       1   
5              32      22      19       3      49      24      23       4   
...           ...     ...     ...     ...     ...     ...     ...     ...   
193581          0       0       0       0       0       0       0       0   
193583          0       0       0       0       0       0       0       0   
193585          0       0       0       0       0       0       0       0   
193587          0       0       0       0       0       0       0       0   
193609          0       0       0       0       0       0       0       0   

movieId_y  9       10      ...  193565  193567  193571  193573  193579  \
movieId_x                  ...                                           
1              12      69  ...       0       0       0       0       0   
2               3      56  ...       0       0       0       0       0   
3               9      23  ...       0       0       0       0       0   
4               0       4  ...       0       0       0       0       0   
5               9      20  ...       0       0       0       0       0   
...           ...     ...  ...     ...     ...     ...     ...     ...   
193581          0       0  ...       1       1       1       1       1   
193583          0       0  ...       1       1       1       1       1   
193585          0       0  ...       1       1       1       1       1   
193587          0       0  ...       1       1       1       1       1   
193609          0       1  ...       0       0       0       0       0   

movieId_y  193581  193583  193585  193587  193609  
movieId_x                                          
1               0       0       0       0       0  
2               0       0       0       0       0  
3               0       0       0       0       0  
4               0       0       0       0       0  
5               0       0       0       0       0  
...           ...     ...     ...     ...     ...  
193581          1       1       1       1       0  
193583          1       1       1       1       0  
193585          1       1       1       1       0  
193587          1       1       1       1       0  
193609          0       0       0       0       1  

[9724 rows x 9724 columns]